# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_parameters', models.TextField(blank=True)),
            ],
        ),
    ]
